name = "xuan-oracle-cup"
main = "src/server/worker.ts"
compatibility_date = "2026-06-24"

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "xuan-oracle-cup"
database_id = "71623528-7b92-4435-8279-891664476eac"

[[kv_namespaces]]
binding = "MARKET_CACHE"
id = "1d5ad6240f484e15a6ca4babd8414147"
